[metadata]
generated_at = "2026-04-30T00:35:19.464300+00:00"
provider = "tikwm"
mode = "video"
hd = false
total_assets = 9

[[assets]]
provider = "tikwm"
media_type = "video"
source_url = "https://vt.tiktok.com/ZS9y5wxK3/"
asset_id = "7634066600399834386"
title = "Cr7 breaks soccer net #ronaldo #Soccer #football #tiktok #edit "
author = "mreditman10"
output_path = "jobs/2026-04-30_001_podcast-karaoke-frame-bongdapodcast/input/raw_assets/videos/non_hd/7634066600399834386_cr7-breaks-soccer-net-ronaldo-soccer-football-tiktok-edit.mp4"
downloaded = true
size_bytes = 1337691
duration_seconds = 15.094
width = 576
height = 1024
direct_url_hash = "14814b38280e"

[[assets]]
provider = "tikwm"
media_type = "video"
source_url = "https://vt.tiktok.com/ZS9ya1W6j/"
asset_id = "7632372541956312342"
title = "cristiano Ronaldo best 4k skills performance ⚽ 🐐#ronaldinho #c7 #alnassr #unfreezemyaccount #foruyou "
author = "ronaldocr7king19"
output_path = "jobs/2026-04-30_001_podcast-karaoke-frame-bongdapodcast/input/raw_assets/videos/non_hd/7632372541956312342_cristiano-ronaldo-best-4k-skills-performance-ronaldinho-c7-alnassr-unf.mp4"
downloaded = true
size_bytes = 3028177
duration_seconds = 30.267
width = 576
height = 1024
direct_url_hash = "51649ce75890"

[[assets]]
provider = "tikwm"
media_type = "video"
source_url = "https://vt.tiktok.com/ZS9y5WfjE/"
asset_id = "7628223214400900374"
title = "Cristiano Ronaldo magical moments ⚽🐐 #ronaldo  #alnasar  #foryoupagee  #viralvideos  #unfreezmyaccount "
author = "cr7_vibes00"
output_path = "jobs/2026-04-30_001_podcast-karaoke-frame-bongdapodcast/input/raw_assets/videos/non_hd/7628223214400900374_cristiano-ronaldo-magical-moments-ronaldo-alnasar-foryoupagee-viralvid.mp4"
downloaded = true
size_bytes = 2405932
duration_seconds = 29.467
width = 576
height = 768
direct_url_hash = "1840eb615266"

[[assets]]
provider = "tikwm"
media_type = "video"
source_url = "https://vt.tiktok.com/ZS9y5qaT3/"
asset_id = "7628268918037105942"
title = "Cristiano Ronaldo 4k skills performance ⚽🐐 #foryoupagee  #foryoupagee  #alnasar  #ronaldo  #unfreezmyaccount "
author = "cr7_vibes00"
output_path = "jobs/2026-04-30_001_podcast-karaoke-frame-bongdapodcast/input/raw_assets/videos/non_hd/7628268918037105942_cristiano-ronaldo-4k-skills-performance-foryoupagee-foryoupagee-alnasa.mp4"
downloaded = true
size_bytes = 3085872
duration_seconds = 33.367
width = 576
height = 1024
direct_url_hash = "8f47b35a9495"

[[assets]]
provider = "tikwm"
media_type = "video"
source_url = "https://vt.tiktok.com/ZS9y5Te1a/"
asset_id = "7633468608416369942"
title = "Cristiano Ronaldo magical moments ⚽🐐 #ronaldo  #alnasar  #foryoupagee  #foryoupagee  #unfreezmyaccount "
author = "cr7_vibes00"
output_path = "jobs/2026-04-30_001_podcast-karaoke-frame-bongdapodcast/input/raw_assets/videos/non_hd/7633468608416369942_cristiano-ronaldo-magical-moments-ronaldo-alnasar-foryoupagee-foryoupa.mp4"
downloaded = true
size_bytes = 2081797
duration_seconds = 29.6
width = 576
height = 710
direct_url_hash = "0057d07bbdc6"

[[assets]]
provider = "tikwm"
media_type = "video"
source_url = "https://vt.tiktok.com/ZS9y5Te1a/"
asset_id = "7633468608416369942"
title = "Cristiano Ronaldo magical moments ⚽🐐 #ronaldo  #alnasar  #foryoupagee  #foryoupagee  #unfreezmyaccount "
author = "cr7_vibes00"
output_path = "jobs/2026-04-30_001_podcast-karaoke-frame-bongdapodcast/input/raw_assets/videos/non_hd/7633468608416369942_cristiano-ronaldo-magical-moments-ronaldo-alnasar-foryoupagee-foryoupa.mp4"
downloaded = false
size_bytes = 2081797
duration_seconds = 29.6
width = 576
height = 710
direct_url_hash = "0057d07bbdc6"

[[assets]]
provider = "tikwm"
media_type = "video"
source_url = "https://vt.tiktok.com/ZS9y53HVb/"
asset_id = "7617445515046767903"
title = "Ronaldo the best world player #CR7 #ronaldo #FootballKing #CristianoRonaldo #ronaldo_fans "
author = "nokblolo"
output_path = "jobs/2026-04-30_001_podcast-karaoke-frame-bongdapodcast/input/raw_assets/videos/non_hd/7617445515046767903_ronaldo-the-best-world-player-cr7-ronaldo-footballking-cristianoronald.mp4"
downloaded = true
size_bytes = 4501929
duration_seconds = 28.9
width = 576
height = 1024
direct_url_hash = "f7d7b6fc0738"

[[assets]]
provider = "tikwm"
media_type = "video"
source_url = "https://vt.tiktok.com/ZS9ya5gvf/"
asset_id = "7633090780071988502"
title = "cristiano Ronaldo magical moment's ⚽🐐#ronaldinho #alnassr #cr #foruyou #unfreezemyaccount "
author = "ronaldocr7king19"
output_path = "jobs/2026-04-30_001_podcast-karaoke-frame-bongdapodcast/input/raw_assets/videos/non_hd/7633090780071988502_cristiano-ronaldo-magical-moments-ronaldinho-alnassr-cr-foruyou-unfree.mp4"
downloaded = true
size_bytes = 3502850
duration_seconds = 30.233
width = 576
height = 1024
direct_url_hash = "58dace52ccb4"

[[assets]]
provider = "tikwm"
media_type = "video"
source_url = "https://vt.tiktok.com/ZS9y5Gsvr/"
asset_id = "7480602529579977991"
title = "Cristiano Ronaldo - Từ Giọt Nước Mắt Tuổi Thơ Đến Đỉnh Cao Huyền Thoại ❤️⚽️ #trending #ronaldo #portugal #viral #hot #ronaldo_cr7 "
author = "davisnguyen1998"
output_path = "jobs/2026-04-30_001_podcast-karaoke-frame-bongdapodcast/input/raw_assets/videos/non_hd/7480602529579977991_cristiano-ronaldo---từ-giọt-nước-mắt-tuổi-thơ-đến-đỉnh-cao-huyền-thoại.mp4"
downloaded = true
size_bytes = 4920009
duration_seconds = 61.4
width = 576
height = 1024
direct_url_hash = "44faed47de4e"
