[metadata]
generated_at = "2026-05-08T06:50:54.624877+00:00"
provider = "tikwm"
mode = "video"
hd = true
total_assets = 1

[[assets]]
provider = "tikwm"
media_type = "video"
source_url = "https://www.tiktok.com/@merotecw/video/7210293452125261058?lang=en&q=nop-ChenYueLong&t=1778222972626"
asset_id = "7210293452125261058"
title = "absolute music | nop -- ChenYueLong.!#nop#music#chill"
author = "merotecw"
output_path = "jobs/2026-05-07_004_tiktok-jenny-lu-n-i-s-v-s-m-nh/input/raw_assets/videos/downloaded/7210293452125261058_absolute-music-nop----chenyuelong.nopmusicchill.mp4"
downloaded = true
size_bytes = 855891
duration_seconds = 103.421
width = 576
height = 576
direct_url_hash = "e1c76f248666"
